language: objective-c
osx_image: xcode6.4

before_install:
- pod install
- xctool clean build
- chmod +x coveralls.sh
- sudo easy_install cpp-coveralls

script:
- xctool test -freshSimulator -freshInstall ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES

after_success:
- ./coveralls.sh