language: objective-c
before_install:
- chmod +x coveralls.sh
- sudo easy_install cpp-coveralls
- pod install
- xctool build
script:
- xctool test -freshSimulator -freshInstall ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
after_success:
- ./coveralls.sh